[project]
name = "dsc190-assignment-6"
version = "0.1.0"
description = "Assignment 6"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "python-dateutil",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
ignore_missing_imports = true

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
